### ISSUE TITLE
Almost everything broken

### ISSUE THREAD

**Issue by SentinelMKX** [Andross96/EasyCalculator#1]
The plugin doesn't register prefix "=" in chat
and when using @=5+5
it shows just the count two times 
like this @=5+5 = 5+5
@=broken = broken
with no results 
1.14.3 Paper ver 124

![image](https://user-images.githubusercontent.com/22961592/60768807-7185ac80-a0c8-11e9-9760-a0f769526289.png)

**Comment by SentinelMKX** [comment]
More info:
When I give myself permission "*" it works, but with "easycalculator.*" it doesn't

**Comment by SentinelMKX** [comment]
A way around that bug is able with adding 
"easycalculator.functions
easycalculator.operations"
permissions, and it works
with "easycalculator.*"" it doesn't work

**Comment by Andross96** [comment]
Hello,

The new update 7.1 should fix all problems.
Thank you for report, and sorry for the response delay.
